

extern const char *quotes[250] = {
    "The map failed because you became the terrain.",
    "Discipline is remembering tomorrow while today begs.",
    "You were not late; the world arrived early.",
    "Silence is what truth sounds like before language ruins it.",
    "Growth hurts because comfort fights back.",
    "The door opened only after you stopped knocking.",
    "Fear rehearses disasters that never bought tickets.",
    "Meaning appears when certainty leaves the room.",
    "You are not behind; you are off the conveyor belt.",
    "Wisdom is curiosity that survived embarrassment.",

    "The shadow proves the light showed up.",
    "Momentum forgives imperfect direction.",
    "Progress rarely announces itself; it just rearranges things.",
    "Your limits learned your name from you.",
    "Confusion is understanding stretching its legs.",
    "Calm is a skill, not a personality trait.",
    "Patience is strength pretending to be still.",
    "The answer hid inside the question’s posture.",
    "You don’t find purpose; you build it quietly.",
    "Fear hates witnesses—bring courage along.",

    "The past only argues when you keep replying.",
    "Most walls are instructions written in fear.",
    "You outgrew the cage; that’s why it rattles.",
    "Doubt sharpens tools before belief swings them.",
    "Clarity comes after the wreckage is sorted.",
    "The brave act tired; the fearful rest busy.",
    "You learned faster once applause stopped.",
    "Hope is realism that hasn’t given up.",
    "The future listens when you stop performing.",
    "Identity is a draft, not a verdict.",

    "Anxiety predicts storms while standing indoors.",
    "You were built for problems, not comfort.",
    "Direction matters more than speed—until momentum matters more than fear.",
    "Discipline is freedom wearing work clothes.",
    "Courage is embarrassment with a backbone.",
    "You became dangerous when you stopped explaining yourself.",
    "Meaning leaks through cracks, not monuments.",
    "Stillness teaches what noise was hiding.",
    "Your instincts matured once approval left.",
    "The long road protects you from shortcuts.",

    "You don’t lack time; you leak it.",
    "Curiosity is rebellion against stale answers.",
    "Pain is a message, not a destination.",
    "You stopped growing when you demanded certainty.",
    "Focus is saying no to louder options.",
    "Confidence grows where comparison dies.",
    "The unknown rewards those who walk anyway.",
    "You didn’t fail—you collected data violently.",
    "Self-respect begins where excuses end.",
    "The climb clarified what comfort obscured.",

    "Doubt keeps sharpening the blade; swing anyway.",
    "You were never lost—just unconvinced.",
    "The mind panics; the body adapts.",
    "Habits shape days; days shape lives.",
    "Meaning hides in repetition done consciously.",
    "Growth is subtraction disguised as addition.",
    "You’re not confused—you’re transitioning.",
    "Stillness is where strategy breathes.",
    "You learned courage by surviving boredom.",
    "Your fear studied you longer than you studied it.",

    "Progress whispers while ego shouts.",
    "The road bends for those who keep walking.",
    "Motivation fades; systems remain.",
    "You cannot rush ripening without ruining flavor.",
    "Insight arrives late but stays longer.",
    "Discipline is kindness to your future self.",
    "You escaped the maze by stopping to observe.",
    "Chaos rearranges priorities honestly.",
    "Strength is choosing again after disappointment.",
    "You don’t need permission from the past.",

    "Reality improves when excuses leave.",
    "Awareness is the beginning of leverage.",
    "Comfort predicts nothing useful.",
    "You found resilience where you stopped complaining.",
    "The mirror lies less than the crowd.",
    "Clarity punishes rushing.",
    "You carry less once you stop proving things.",
    "Vision sharpens when options narrow.",
    "Fear grows when unchallenged; courage grows challenged.",
    "You became reliable when motivation failed.",

    "Silence trains discernment.",
    "You don’t chase meaning—you practice it.",
    "Attention is the rarest currency.",
    "You can’t optimize what you won’t examine.",
    "Momentum forgives awkward beginnings.",
    "The unknown respects preparation, not confidence.",
    "You outpaced doubt by refusing debate.",
    "Curiosity survives where certainty suffocates.",
    "Stillness unmasks unnecessary urgency.",
    "Growth often feels like loss first.",

    "You learned patience by needing results.",
    "Fear is creative; so is courage.",
    "The climb rewired your standards.",
    "Clarity arrives after endurance.",
    "You stopped fearing judgment when you started judging less.",
    "Progress is quiet until undeniable.",
    "Insight prefers discomfort.",
    "You don’t lack discipline; you lack structure.",
    "Time reveals what effort conceals.",
    "You matured when comfort bored you.",

    "Truth doesn’t rush; it waits.",
    "Focus grows where distraction starves.",
    "You stopped arguing with reality and started working with it.",
    "The unknown became manageable once named.",
    "Direction outruns enthusiasm.",
    "You discovered strength by finishing tired.",
    "Insight blooms under pressure.",
    "You don’t rise to goals; you fall to systems.",
    "Fear collapses when faced daily.",
    "You grew quieter and stronger simultaneously.",

    "The path clarified itself after commitment.",
    "You stopped searching when you started building.",
    "Chaos simplifies priorities brutally.",
    "Discipline is motivation’s dependable cousin.",
    "You found leverage by slowing down.",
    "Clarity is earned, not downloaded.",
    "The obstacle was instructional.",
    "You learned confidence by surviving mistakes.",
    "Attention decides reality’s shape.",
    "Growth demands repetition without applause.",

    "You weren’t stuck—you were incubating.",
    "Courage is fear carrying responsibility.",
    "The process taught what results couldn’t.",
    "You became capable when excuses expired.",
    "Stillness sharpened perception.",
    "The unknown shrinks under consistent action.",
    "You stopped fearing failure once you met it.",
    "Direction steadies chaos.",
    "Insight is patience paying interest.",
    "You learned resilience by finishing anyway.",

    "The path rewards presence, not speed.",
    "You outgrew explanations.",
    "Focus multiplies effort.",
    "The mind resists change; reality enforces it.",
    "You earned clarity by enduring ambiguity.",
    "Growth starts when comfort protests.",
    "Courage sounds like quiet commitment.",
    "You simplified once complexity failed.",
    "Awareness dismantles illusions gently.",
    "You learned strength by carrying boredom.",

    "Meaning accumulates through consistency.",
    "You stopped negotiating with fear.",
    "Insight often arrives inconveniently.",
    "The work taught you who you are.",
    "You didn’t lose direction—you refined it.",
    "Discipline protects energy.",
    "The unknown softened under routine.",
    "You learned patience when rushing failed.",
    "Focus converts chaos into sequence.",
    "You matured when excuses embarrassed you.",

    "Growth reveals what mattered all along.",
    "The climb disciplined your expectations.",
    "Courage improves with repetition.",
    "You learned clarity through friction.",
    "Stillness exposes unnecessary noise.",
    "The future respects preparation.",
    "You stopped seeking certainty and gained traction.",
    "Progress hides in boring consistency.",
    "Insight is curiosity that endured.",
    "You found power by choosing again.",

    "Direction calms fear.",
    "You trained resilience by finishing unfocused days.",
    "Meaning resists shortcuts.",
    "You stopped fearing effort once it paid off.",
    "Discipline is trust built daily.",
    "The path clarified itself through action.",
    "You became patient out of necessity.",
    "Focus punishes distraction honestly.",
    "Growth makes old goals obsolete.",
    "You learned courage through repetition.",

    "Clarity followed endurance.",
    "You became grounded by removing options.",
    "Insight prefers discomfort over comfort.",
    "You stopped arguing and started aligning.",
    "The unknown cooperates with consistency.",
    "You outlasted doubt quietly.",
    "Strength is sustained effort without applause.",
    "You learned confidence by surviving boredom.",
    "Meaning assembled itself slowly.",
    "You found freedom through structure.",

    "Discipline replaces motivation eventually.",
    "You sharpened focus by removing noise.",
    "Growth reorders priorities ruthlessly.",
    "You stopped chasing inspiration and built habits.",
    "Courage matured into reliability.",
    "You learned patience from long timelines.",
    "Insight is earned through repetition.",
    "You became steady by accepting uncertainty.",
    "Progress respects commitment.",
    "You stopped waiting and started shaping.",

    "Stillness recalibrates ambition.",
    "You didn’t quit—you redirected.",
    "Discipline trains confidence quietly.",
    "You learned clarity by subtracting.",
    "Growth requires boring bravery.",
    "You outgrew urgency.",
    "Focus revealed leverage.",
    "You matured through consistency.",
    "Insight followed endurance.",
    "You became capable by showing up.",

    "Courage stabilized into habit.",
    "You stopped fearing effort.",
    "The process trained you well.",
    "Growth simplified you.",
    "You learned meaning by repetition.",
    "Focus created momentum.",
    "Discipline shaped identity.",
    "You earned clarity slowly.",
    "Courage became routine.",
    "You finished tired, anyway.",

    "Meaning accumulated quietly.",
    "You chose consistency over intensity.",
    "Growth punished excuses.",
    "You stabilized through discipline.",
    "Insight rewarded patience.",
    "You learned resilience practically.",
    "Focus defeated distraction.",
    "You became dependable.",
    "Courage turned ordinary.",
    "You built momentum.",

    "Meaning emerged gradually.",
    "You committed without certainty.",
    "Growth demanded endurance.",
    "Discipline replaced motivation.",
    "You learned strength repeatedly.",
    "Focus simplified effort.",
    "Courage survived boredom.",
    "You became reliable.",
    "Insight followed work.",
    "You stayed the course.",

    "Meaning rewarded patience.",
    "You chose structure.",
    "Growth respected effort.",
    "Discipline endured.",
    "Focus remained.",
    "Courage stabilized.",
    "You persisted.",
    "Insight arrived.",
    "You matured.",
    "Momentum carried you.",

    "Meaning stayed.",
    "You continued.",
    "Growth integrated.",
    "Discipline held.",
    "Focus clarified.",
    "Courage remained.",
    "You finished.",
    "Insight settled.",
    "You endured.",
    "You became."
};
